### ISSUE TITLE
v25.2.0 not published to npm?

### ISSUE THREAD

**Issue by eatonphil** [electron/chromedriver#120]
The latest 25.x release on npm is 25.1.1. https://www.npmjs.com/package/electron-chromedriver?activeTab=versions.

But 25.2.0 was published last week https://github.com/electron/chromedriver/releases/tag/v25.2.0.

Am I missing something or has this one not been published to npm for some reason?

Thanks!

**Comment by dsanders11** [comment]
Thanks for the report! It looks like that release [failed to publish to npm](https://app.circleci.com/pipelines/github/electron/chromedriver/161/workflows/43409c63-1e27-4fee-9ed8-61c83ffe9d40/jobs/548), due to a server error. Looks like around 5 versions didn't publish during that time period, but the most recent ones have succeeded.

Using version 25.1.1 should work fine for your needs - we used to only publish one version of chromedriver per major Electron release (so 25.0.0) as that should be sufficient, but recently switched to publishing 1:1 versions in case there's any fixes relevant to chromedriver to pick up.
