### ISSUE TITLE
arm64 version?

### ISSUE THREAD

**Issue by theschles** [electron/chromedriver#16]
Hi there,

I'm trying to build the Atom IDE on Ubuntu on an Odroid-C2 -- it's arm64 based.

It's failing because -- by the looks of the error message below -- there is no arm64 version of chromedriver v2.21.  Would you please build an arm64 version?

Thanks, Phil

`odroid@odroid64:~/Downloads/atom$ script/build --create-debian-package
Node:	v6.9.5
Npm:	v4.1.2
Installing script dependencies
Downloading https://github.com/electron/electron/releases/download/v1.3.0/chromedriver-v2.21-linux-arm64.zip failed: Non-200 response (404)
npm ERR! Linux 3.14.79-105
npm ERR! argv "/usr/bin/node" "/home/odroid/.npm-global/bin/npm" "--loglevel=error" "install"
npm ERR! node v6.9.5
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE

npm ERR! electron-chromedriver@1.3.2 install: `node ./download-chromedriver.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron-chromedriver@1.3.2 install script 'node ./download-chromedriver.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron-chromedriver package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./download-chromedriver.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron-chromedriver
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron-chromedriver
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
`

**Comment by theschles** [comment]
[npm-debug.log.txt](https://github.com/electron/chromedriver/files/743999/npm-debug.log.txt)

**Comment by kevinsawicki** [comment]
Electron does not yet support arm64, please subscribe to https://github.com/electron/electron/issues/5706 for updates.

**Comment by brasilikum** [comment]
I think this is relevant again, now that electron supports arm64.
I came here because I discovered that webtorrent does not build because this dependency fails.

https://github.com/webtorrent/webtorrent-desktop/issues/1907

**Comment by erickzhao** [comment]
@brasilikum The logs you posted in the linked issue are pertinent here.

During installation,  the `electron-chromedriver` binary gets downloaded through Electron's GitHub release artifacts.

```
GotError [HTTPError]: Response code 404 (Not Found) for https://github.com/electron/electron/releases/download/v10.0.0/chromedriver-v10.0.0-darwin-arm64.zip
```

In this case, you're getting a 404 response because there's no `darwin-arm64` binary for [Electron v10.0.0](https://github.com/electron/electron/releases/tag/v10.0.0). This is normal because Apple Silicon support for Electron only came with Electron 11.

Looking at the webtorrent desktop dependency [lockfile](https://github.com/webtorrent/webtorrent-desktop/blob/f0894ced5496f3506f76d49d2a5facdbcae0ba9e/package-lock.json#L3531), you should probably ensure your version of `electron-chromedriver` is `v11.0.0`.

**Comment by brasilikum** [comment]
Perfecto, thanks for the pointer
