### ISSUE TITLE
Wrong version of chromedriver downloaded?

### ISSUE THREAD

**Issue by alex-dow** [electron/chromedriver#56]
Electron is pegged to v7.1.9 and electron-chromedriver to v7.0.0

electron-chromedriver attempts to download chromdriver v7.0.0 as well, but

https://github.com/electron/electron/releases/tag/v7.1.9

seems there are 7.1.9 binaries of chromedriver which I expected electron-chromedriver to download.

Is this expected behaviour?

**Comment by jamesjin** [comment]
have the same issue here.

download-chromedriver.js  uses its own package.json version instead of electron's version.

however, chromedriver uses electron's version, e.g. 

chromedriver-v7.1.14-win32-x64.zip

**Comment by jkleinsc** [comment]
It is the expected behaviour.  Chromedriver really only changes on the major chromium versions so the 7.1.9 chromedriver binary should be the same as the 7.0.0 binary.  If you really want a specific version you can use version 9.0.0 or later of this package to download a specific version.  Eg: `ELECTRON_CUSTOM_VERSION=7.1.9 npm install`
