### ISSUE TITLE
Chromedriver can resize or get the resolution of a window from Electron Application using Java

### ISSUE THREAD

**Issue by michael-lam** [electron/chromedriver#72]
Hi team,

I am testing an Electron app and there are some libraries I am using:
- Electron version 10.1.5
- Using Java
- Selenium 3.141.59
- Use electron-chromedriver version 10.1.5

There are some problems I faced like:
1. I cannot get a window dimension
2. Cannot resize with a specific resolution

Is there any solution to these issues?

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.
